#!/bin/bash
# Manual deployment steps for Coolify

echo "=== Coolify Manual Deployment Guide ==="
echo ""
echo "Please follow these steps in your Coolify dashboard:"
echo ""
echo "1. LOGIN TO COOLIFY"
echo "   - Go to your Coolify instance"
echo "   - Login with your credentials"
echo ""
echo "2. STOP CURRENT SITE (if exists)"
echo "   - Find your current 'benniewilliams' application"
echo "   - Click on it and press 'Stop'"
echo "   - DO NOT DELETE - keep as backup"
echo ""
echo "3. CREATE NEW APPLICATION"
echo "   - Click 'New' → 'Application'"
echo "   - Choose 'Public Repository'"
echo "   - Enter: https://github.com/MDsniper/benniewilliams-wagtail"
echo "   - Branch: main"
echo "   - Build Pack: Dockerfile"
echo ""
echo "4. CONFIGURE SETTINGS"
echo "   Application Name: benniewilliams-wagtail"
echo "   Port: 8000"
echo "   Health Check Path: /"
echo ""
echo "5. ADD ENVIRONMENT VARIABLES"
echo "   Click on 'Environment Variables' and add:"
echo ""
echo "   SECRET_KEY=$(python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')"
echo "   ALLOWED_HOSTS=benniewilliams.com,www.benniewilliams.com"
echo "   DJANGO_SETTINGS_MODULE=benniewilliams.settings.production"
echo "   DEBUG=False"
echo ""
echo "6. CONFIGURE DOMAINS"
echo "   - Add: benniewilliams.com"
echo "   - Add: www.benniewilliams.com"
echo "   - Enable 'Force HTTPS'"
echo "   - Enable 'Auto-generate SSL'"
echo ""
echo "7. CONFIGURE STORAGE (Optional but recommended)"
echo "   Add persistent volumes:"
echo "   - /app/media → Named volume: media"
echo "   - /app/static → Named volume: static"
echo ""
echo "8. DEPLOY"
echo "   - Click 'Deploy'"
echo "   - Monitor logs for any issues"
echo "   - Wait for 'Deployment successful' message"
echo ""
echo "9. CREATE ADMIN USER (After deployment)"
echo "   - Go to the 'Terminal' tab in Coolify"
echo "   - Run: python manage.py createsuperuser"
echo "   - Follow prompts to create admin account"
echo ""
echo "10. VERIFY"
echo "   - Visit https://benniewilliams.com"
echo "   - Check About page for your Gravatar image"
echo "   - Visit https://benniewilliams.com/admin for admin panel"
echo ""
echo "=== Generated Secret Key (save this): ==="
python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
echo ""
echo "Copy the above SECRET_KEY and use it in step 5!"