#!/bin/bash

# Coolify Deployment Script
# This script provides the exact commands to deploy your site

echo "════════════════════════════════════════════════════════"
echo "       COOLIFY DEPLOYMENT - BENNIEWILLIAMS.COM         "
echo "════════════════════════════════════════════════════════"
echo ""

# Generate a secure secret key
SECRET_KEY=$(python3 -c "import secrets; import string; chars = string.ascii_letters + string.digits + '!@#%^&*(-_=+)'; print(''.join(secrets.choice(chars) for _ in range(50)))" 2>/dev/null || echo "CHANGE-THIS-TO-A-SECURE-50-CHARACTER-KEY-NOW")

echo "📋 DEPLOYMENT CHECKLIST:"
echo "========================"
echo ""
echo "1️⃣  LOGIN TO COOLIFY"
echo "   URL: https://coolify.yourdomain.com"
echo ""
echo "2️⃣  CREATE NEW APPLICATION"
echo "   • Click: + New Resource"
echo "   • Select: Public Repository"
echo ""
echo "3️⃣  CONFIGURE REPOSITORY"
echo "   ┌────────────────────────────────────────────────┐"
echo "   │ Repository URL:                                │"
echo "   │ https://github.com/MDsniper/benniewilliams-wagtail │"
echo "   │                                                │"
echo "   │ Branch: main                                   │"
echo "   │ Build Pack: Dockerfile                         │"
echo "   └────────────────────────────────────────────────┘"
echo ""
echo "4️⃣  BASIC CONFIGURATION"
echo "   • Name: benniewilliams"
echo "   • Port: 8000"
echo ""
echo "5️⃣  ENVIRONMENT VARIABLES (Copy exactly):"
echo "   ┌────────────────────────────────────────────────┐"
echo "   │ Click 'Environment Variables' and add:        │"
echo "   └────────────────────────────────────────────────┘"
echo ""
echo "SECRET_KEY=$SECRET_KEY"
echo "DJANGO_SETTINGS_MODULE=benniewilliams.settings.production"
echo "ALLOWED_HOSTS=benniewilliams.com,www.benniewilliams.com,localhost"
echo "DEBUG=False"
echo "SECURE_SSL_REDIRECT=True"
echo "SESSION_COOKIE_SECURE=True"
echo "CSRF_COOKIE_SECURE=True"
echo ""
echo "6️⃣  DOMAINS CONFIGURATION"
echo "   • Add Domain: benniewilliams.com"
echo "   • Add Domain: www.benniewilliams.com"
echo "   • ✅ Enable: Generate SSL Certificate"
echo "   • ✅ Enable: Force HTTPS Redirect"
echo ""
echo "7️⃣  HEALTH CHECK"
echo "   • Health Check Path: /health/"
echo "   • Health Check Interval: 30"
echo ""
echo "8️⃣  RESOURCE LIMITS (Optional)"
echo "   • CPU: 1"
echo "   • Memory: 1GB"
echo ""
echo "9️⃣  PERSISTENT STORAGE (Recommended)"
echo "   Add Volumes:"
echo "   • /app/media → volume name: media"
echo "   • /app/static → volume name: static"
echo ""
echo "🚀 DEPLOY"
echo "   • Click: Deploy"
echo "   • Watch logs for: 'Starting gunicorn'"
echo ""
echo "════════════════════════════════════════════════════════"
echo "⏱️  ESTIMATED DEPLOYMENT TIME: 5-10 minutes"
echo "════════════════════════════════════════════════════════"
echo ""
echo "📌 AFTER DEPLOYMENT:"
echo "   1. Visit: https://benniewilliams.com"
echo "   2. Check: /about page for your Gravatar"
echo "   3. Admin: https://benniewilliams.com/admin"
echo ""
echo "💡 TROUBLESHOOTING:"
echo "   • If deploy fails: Check 'Logs' tab"
echo "   • If site doesn't load: Verify port is 8000"
echo "   • If SSL fails: Check domain DNS points to server"
echo ""
echo "Press ENTER to confirm you've copied the above information..."
read -r

echo ""
echo "🎉 Good luck with your deployment!"
echo "   Repository: https://github.com/MDsniper/benniewilliams-wagtail"
echo "   Support: Check COOLIFY_DEPLOYMENT_GUIDE.md for details"
echo ""