# Generated by Django 5.2.6 on 2025-09-19 09:58

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "email",
                    models.EmailField(
                        default="bennie@benniewilliams.com", max_length=254
                    ),
                ),
                (
                    "thank_you_text",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Text to display after form submission"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CoursesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("block_quote", 3),
                            ("embed", 4),
                            ("raw_html", 5),
                            ("code", 8),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "full title",
                                    "icon": "title",
                                    "template": "blocks/heading.html",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "icon": "pilcrow",
                                    "template": "blocks/paragraph.html",
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"icon": "image", "template": "blocks/image.html"},
                            ),
                            3: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {
                                    "icon": "openquote",
                                    "template": "blocks/blockquote.html",
                                },
                            ),
                            4: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"icon": "media", "template": "blocks/embed.html"},
                            ),
                            5: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {"icon": "code", "template": "blocks/raw_html.html"},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("python", "Python"),
                                        ("javascript", "JavaScript"),
                                        ("html", "HTML"),
                                        ("css", "CSS"),
                                        ("bash", "Bash"),
                                    ]
                                },
                            ),
                            7: ("wagtail.blocks.TextBlock", (), {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 6), ("code", 7)]],
                                {"icon": "code", "template": "blocks/code.html"},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ServicesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("block_quote", 3),
                            ("embed", 4),
                            ("raw_html", 5),
                            ("code", 8),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "full title",
                                    "icon": "title",
                                    "template": "blocks/heading.html",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "icon": "pilcrow",
                                    "template": "blocks/paragraph.html",
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"icon": "image", "template": "blocks/image.html"},
                            ),
                            3: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {
                                    "icon": "openquote",
                                    "template": "blocks/blockquote.html",
                                },
                            ),
                            4: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"icon": "media", "template": "blocks/embed.html"},
                            ),
                            5: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {"icon": "code", "template": "blocks/raw_html.html"},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("python", "Python"),
                                        ("javascript", "JavaScript"),
                                        ("html", "HTML"),
                                        ("css", "CSS"),
                                        ("bash", "Bash"),
                                    ]
                                },
                            ),
                            7: ("wagtail.blocks.TextBlock", (), {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 6), ("code", 7)]],
                                {"icon": "code", "template": "blocks/code.html"},
                            ),
                        },
                    ),
                ),
                (
                    "consultation_price",
                    models.CharField(
                        default="$250/hour",
                        help_text="Consultation pricing",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("block_quote", 3),
                            ("embed", 4),
                            ("raw_html", 5),
                            ("code", 8),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "full title",
                                    "icon": "title",
                                    "template": "blocks/heading.html",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "icon": "pilcrow",
                                    "template": "blocks/paragraph.html",
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"icon": "image", "template": "blocks/image.html"},
                            ),
                            3: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {
                                    "icon": "openquote",
                                    "template": "blocks/blockquote.html",
                                },
                            ),
                            4: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"icon": "media", "template": "blocks/embed.html"},
                            ),
                            5: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {"icon": "code", "template": "blocks/raw_html.html"},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("python", "Python"),
                                        ("javascript", "JavaScript"),
                                        ("html", "HTML"),
                                        ("css", "CSS"),
                                        ("bash", "Bash"),
                                    ]
                                },
                            ),
                            7: ("wagtail.blocks.TextBlock", (), {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 6), ("code", 7)]],
                                {"icon": "code", "template": "blocks/code.html"},
                            ),
                        },
                    ),
                ),
                (
                    "profile_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Post date")),
                ("author", models.CharField(default="Bennie Williams", max_length=255)),
                ("intro", models.CharField(max_length=500)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("block_quote", 3),
                            ("embed", 4),
                            ("raw_html", 5),
                            ("code", 8),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "full title",
                                    "icon": "title",
                                    "template": "blocks/heading.html",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "icon": "pilcrow",
                                    "template": "blocks/paragraph.html",
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"icon": "image", "template": "blocks/image.html"},
                            ),
                            3: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {
                                    "icon": "openquote",
                                    "template": "blocks/blockquote.html",
                                },
                            ),
                            4: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"icon": "media", "template": "blocks/embed.html"},
                            ),
                            5: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {"icon": "code", "template": "blocks/raw_html.html"},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("python", "Python"),
                                        ("javascript", "JavaScript"),
                                        ("html", "HTML"),
                                        ("css", "CSS"),
                                        ("bash", "Bash"),
                                    ]
                                },
                            ),
                            7: ("wagtail.blocks.TextBlock", (), {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 6), ("code", 7)]],
                                {"icon": "code", "template": "blocks/code.html"},
                            ),
                        },
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="home.blogpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="blogpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="home.BlogPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("description", wagtail.fields.RichTextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gumroad_link", models.URLField(help_text="Gumroad purchase link")),
                (
                    "youtube_preview_id",
                    models.CharField(
                        blank=True,
                        help_text="YouTube video ID for preview (unlisted)",
                        max_length=50,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Bennie Williams",
                        help_text="Hero section title",
                        max_length=255,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="AI Consultant & Educator",
                        help_text="Hero section subtitle",
                        max_length=500,
                    ),
                ),
                (
                    "hero_cta_text",
                    models.CharField(
                        default="Work With Me",
                        help_text="Hero CTA button text",
                        max_length=100,
                    ),
                ),
                (
                    "hero_cta_link",
                    models.URLField(blank=True, help_text="Hero CTA button link"),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("block_quote", 3),
                            ("embed", 4),
                            ("raw_html", 5),
                            ("code", 8),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "full title",
                                    "icon": "title",
                                    "template": "blocks/heading.html",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "icon": "pilcrow",
                                    "template": "blocks/paragraph.html",
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"icon": "image", "template": "blocks/image.html"},
                            ),
                            3: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {
                                    "icon": "openquote",
                                    "template": "blocks/blockquote.html",
                                },
                            ),
                            4: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"icon": "media", "template": "blocks/embed.html"},
                            ),
                            5: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {"icon": "code", "template": "blocks/raw_html.html"},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("python", "Python"),
                                        ("javascript", "JavaScript"),
                                        ("html", "HTML"),
                                        ("css", "CSS"),
                                        ("bash", "Bash"),
                                    ]
                                },
                            ),
                            7: ("wagtail.blocks.TextBlock", (), {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 6), ("code", 7)]],
                                {"icon": "code", "template": "blocks/code.html"},
                            ),
                        },
                    ),
                ),
                (
                    "featured_blog_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="home.blogpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
