# Generated by Django 5.2.6 on 2025-09-25 22:18

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogindexpage_contactpage_alter_homepage_options_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('profile_statement', models.TextField(blank=True, help_text='Main profile/introduction statement')),
                ('career_timeline', wagtail.fields.StreamField([('milestone', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('year', 0), ('title', 1), ('organization', 2), ('description', 3)]], {})})),
                ('expertise_areas', wagtail.fields.StreamField([('skill', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.IntegerBlock', (), {'max_value': 100, 'min_value': 0}), 2: ('wagtail.blocks.StructBlock', [[('area', 0), ('level', 1)]], {})})),
                ('values', wagtail.fields.StreamField([('value', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 5}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {})})),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('services', wagtail.fields.StreamField([('service', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 5}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2), ('features', 4)]], {})})),
            ],
            options={
                'verbose_name': 'Services Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
